// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.hi.dhl.datastore.protobuf;

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>bool followAccount = 3;</code>
     * @return The followAccount.
     */
    boolean getFollowAccount();

    /**
     * <code>repeated string phone = 4;</code>
     * @return A list containing the phone.
     */
    java.util.List<java.lang.String>
        getPhoneList();
    /**
     * <code>repeated string phone = 4;</code>
     * @return The count of phone.
     */
    int getPhoneCount();
    /**
     * <code>repeated string phone = 4;</code>
     * @param index The index of the element to return.
     * @return The phone at the given index.
     */
    java.lang.String getPhone(int index);
    /**
     * <code>repeated string phone = 4;</code>
     * @param index The index of the element to return.
     * @return The phone at the given index.
     */
    com.google.protobuf.ByteString
        getPhoneBytes(int index);

    /**
     * <code>.Person.Address address = 5;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>.Person.Address address = 5;</code>
     * @return The address.
     */
    com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address getAddress();

    /**
     * <code>.Person.Weekday weekday = 6;</code>
     * @return The enum numeric value on the wire for weekday.
     */
    int getWeekdayValue();
    /**
     * <code>.Person.Weekday weekday = 6;</code>
     * @return The weekday.
     */
    com.hi.dhl.datastore.protobuf.PersonProtos.Person.Weekday getWeekday();
  }
  /**
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageLite<
          Person, Person.Builder> implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
    private Person() {
      name_ = "";
      phone_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * Protobuf enum {@code Person.Weekday}
     */
    public enum Weekday
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>SUN = 0;</code>
       */
      SUN(0),
      /**
       * <code>MON = 1;</code>
       */
      MON(1),
      /**
       * <code>TUE = 2;</code>
       */
      TUE(2),
      /**
       * <code>WED = 3;</code>
       */
      WED(3),
      /**
       * <code>THU = 4;</code>
       */
      THU(4),
      /**
       * <code>FRI = 5;</code>
       */
      FRI(5),
      /**
       * <code>SAT = 6;</code>
       */
      SAT(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SUN = 0;</code>
       */
      public static final int SUN_VALUE = 0;
      /**
       * <code>MON = 1;</code>
       */
      public static final int MON_VALUE = 1;
      /**
       * <code>TUE = 2;</code>
       */
      public static final int TUE_VALUE = 2;
      /**
       * <code>WED = 3;</code>
       */
      public static final int WED_VALUE = 3;
      /**
       * <code>THU = 4;</code>
       */
      public static final int THU_VALUE = 4;
      /**
       * <code>FRI = 5;</code>
       */
      public static final int FRI_VALUE = 5;
      /**
       * <code>SAT = 6;</code>
       */
      public static final int SAT_VALUE = 6;


      @java.lang.Override
      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Weekday valueOf(int value) {
        return forNumber(value);
      }

      public static Weekday forNumber(int value) {
        switch (value) {
          case 0: return SUN;
          case 1: return MON;
          case 2: return TUE;
          case 3: return WED;
          case 4: return THU;
          case 5: return FRI;
          case 6: return SAT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Weekday>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Weekday> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Weekday>() {
              @java.lang.Override
              public Weekday findValueByNumber(int number) {
                return Weekday.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return WeekdayVerifier.INSTANCE;
      }

      private static final class WeekdayVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new WeekdayVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return Weekday.forNumber(number) != null;
              }
            };

      private final int value;

      private Weekday(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.Weekday)
    }

    public interface AddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Person.Address)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>string city = 1;</code>
       * @return The city.
       */
      java.lang.String getCity();
      /**
       * <code>string city = 1;</code>
       * @return The bytes for city.
       */
      com.google.protobuf.ByteString
          getCityBytes();
    }
    /**
     * Protobuf type {@code Person.Address}
     */
    public  static final class Address extends
        com.google.protobuf.GeneratedMessageLite<
            Address, Address.Builder> implements
        // @@protoc_insertion_point(message_implements:Person.Address)
        AddressOrBuilder {
      private Address() {
        city_ = "";
      }
      public static final int CITY_FIELD_NUMBER = 1;
      private java.lang.String city_;
      /**
       * <code>string city = 1;</code>
       * @return The city.
       */
      @java.lang.Override
      public java.lang.String getCity() {
        return city_;
      }
      /**
       * <code>string city = 1;</code>
       * @return The bytes for city.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCityBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(city_);
      }
      /**
       * <code>string city = 1;</code>
       * @param value The city to set.
       */
      private void setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
      }
      /**
       * <code>string city = 1;</code>
       */
      private void clearCity() {
        
        city_ = getDefaultInstance().getCity();
      }
      /**
       * <code>string city = 1;</code>
       * @param value The bytes for city to set.
       */
      private void setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value.toStringUtf8();
      }

      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code Person.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address, Builder> implements
          // @@protoc_insertion_point(builder_implements:Person.Address)
          com.hi.dhl.datastore.protobuf.PersonProtos.Person.AddressOrBuilder {
        // Construct using com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>string city = 1;</code>
         * @return The city.
         */
        @java.lang.Override
        public java.lang.String getCity() {
          return instance.getCity();
        }
        /**
         * <code>string city = 1;</code>
         * @return The bytes for city.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getCityBytes() {
          return instance.getCityBytes();
        }
        /**
         * <code>string city = 1;</code>
         * @param value The city to set.
         * @return This builder for chaining.
         */
        public Builder setCity(
            java.lang.String value) {
          copyOnWrite();
          instance.setCity(value);
          return this;
        }
        /**
         * <code>string city = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearCity() {
          copyOnWrite();
          instance.clearCity();
          return this;
        }
        /**
         * <code>string city = 1;</code>
         * @param value The bytes for city to set.
         * @return This builder for chaining.
         */
        public Builder setCityBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setCityBytes(value);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Person.Address)
      }
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "city_",
              };
              java.lang.String info =
                  "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address> parser = PARSER;
            if (parser == null) {
              synchronized (com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address.class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address>(
                          DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:Person.Address)
      private static final com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address DEFAULT_INSTANCE;
      static {
        Address defaultInstance = new Address();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          Address.class, defaultInstance);
      }

      public static com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Address> PARSER;

      public static com.google.protobuf.Parser<Address> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value.toStringUtf8();
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     */
    private void setAge(int value) {
      
      age_ = value;
    }
    /**
     * <code>int32 age = 2;</code>
     */
    private void clearAge() {
      
      age_ = 0;
    }

    public static final int FOLLOWACCOUNT_FIELD_NUMBER = 3;
    private boolean followAccount_;
    /**
     * <code>bool followAccount = 3;</code>
     * @return The followAccount.
     */
    @java.lang.Override
    public boolean getFollowAccount() {
      return followAccount_;
    }
    /**
     * <code>bool followAccount = 3;</code>
     * @param value The followAccount to set.
     */
    private void setFollowAccount(boolean value) {
      
      followAccount_ = value;
    }
    /**
     * <code>bool followAccount = 3;</code>
     */
    private void clearFollowAccount() {
      
      followAccount_ = false;
    }

    public static final int PHONE_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> phone_;
    /**
     * <code>repeated string phone = 4;</code>
     * @return A list containing the phone.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getPhoneList() {
      return phone_;
    }
    /**
     * <code>repeated string phone = 4;</code>
     * @return The count of phone.
     */
    @java.lang.Override
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <code>repeated string phone = 4;</code>
     * @param index The index of the element to return.
     * @return The phone at the given index.
     */
    @java.lang.Override
    public java.lang.String getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <code>repeated string phone = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phone at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          phone_.get(index));
    }
    private void ensurePhoneIsMutable() {
      if (!phone_.isModifiable()) {
        phone_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(phone_);
       }
    }
    /**
     * <code>repeated string phone = 4;</code>
     * @param index The index to set the value at.
     * @param value The phone to set.
     */
    private void setPhone(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneIsMutable();
      phone_.set(index, value);
    }
    /**
     * <code>repeated string phone = 4;</code>
     * @param value The phone to add.
     */
    private void addPhone(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneIsMutable();
      phone_.add(value);
    }
    /**
     * <code>repeated string phone = 4;</code>
     * @param values The phone to add.
     */
    private void addAllPhone(
        java.lang.Iterable<java.lang.String> values) {
      ensurePhoneIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, phone_);
    }
    /**
     * <code>repeated string phone = 4;</code>
     */
    private void clearPhone() {
      phone_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string phone = 4;</code>
     * @param value The bytes of the phone to add.
     */
    private void addPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePhoneIsMutable();
      phone_.add(value.toStringUtf8());
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address address_;
    /**
     * <code>.Person.Address address = 5;</code>
     */
    @java.lang.Override
    public boolean hasAddress() {
      return address_ != null;
    }
    /**
     * <code>.Person.Address address = 5;</code>
     */
    @java.lang.Override
    public com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address getAddress() {
      return address_ == null ? com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>.Person.Address address = 5;</code>
     */
    private void setAddress(com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address value) {
      if (value == null) {
        throw new NullPointerException();
      }
      address_ = value;
      
      }
    /**
     * <code>.Person.Address address = 5;</code>
     */
    private void setAddress(
        com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address.Builder builderForValue) {
      address_ = builderForValue.build();
      
    }
    /**
     * <code>.Person.Address address = 5;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeAddress(com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (address_ != null &&
          address_ != com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address.getDefaultInstance()) {
        address_ =
          com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address.newBuilder(address_).mergeFrom(value).buildPartial();
      } else {
        address_ = value;
      }
      
    }
    /**
     * <code>.Person.Address address = 5;</code>
     */
    private void clearAddress() {  address_ = null;
      
    }

    public static final int WEEKDAY_FIELD_NUMBER = 6;
    private int weekday_;
    /**
     * <code>.Person.Weekday weekday = 6;</code>
     * @return The enum numeric value on the wire for weekday.
     */
    @java.lang.Override
    public int getWeekdayValue() {
      return weekday_;
    }
    /**
     * <code>.Person.Weekday weekday = 6;</code>
     * @return The weekday.
     */
    @java.lang.Override
    public com.hi.dhl.datastore.protobuf.PersonProtos.Person.Weekday getWeekday() {
      com.hi.dhl.datastore.protobuf.PersonProtos.Person.Weekday result = com.hi.dhl.datastore.protobuf.PersonProtos.Person.Weekday.forNumber(weekday_);
      return result == null ? com.hi.dhl.datastore.protobuf.PersonProtos.Person.Weekday.UNRECOGNIZED : result;
    }
    /**
     * <code>.Person.Weekday weekday = 6;</code>
     * @param value The enum numeric value on the wire for weekday to set.
     */
    private void setWeekdayValue(int value) {
        weekday_ = value;
    }
    /**
     * <code>.Person.Weekday weekday = 6;</code>
     * @param value The weekday to set.
     */
    private void setWeekday(com.hi.dhl.datastore.protobuf.PersonProtos.Person.Weekday value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      weekday_ = value.getNumber();
    }
    /**
     * <code>.Person.Weekday weekday = 6;</code>
     */
    private void clearWeekday() {
      
      weekday_ = 0;
    }

    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.hi.dhl.datastore.protobuf.PersonProtos.Person prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.hi.dhl.datastore.protobuf.PersonProtos.Person, Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        com.hi.dhl.datastore.protobuf.PersonProtos.PersonOrBuilder {
      // Construct using com.hi.dhl.datastore.protobuf.PersonProtos.Person.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 格式：字段类型 + 字段名称 + 字段编号
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <pre>
       * 格式：字段类型 + 字段名称 + 字段编号
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <pre>
       * 格式：字段类型 + 字段名称 + 字段编号
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <pre>
       * 格式：字段类型 + 字段名称 + 字段编号
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <pre>
       * 格式：字段类型 + 字段名称 + 字段编号
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return instance.getAge();
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        copyOnWrite();
        instance.setAge(value);
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        copyOnWrite();
        instance.clearAge();
        return this;
      }

      /**
       * <code>bool followAccount = 3;</code>
       * @return The followAccount.
       */
      @java.lang.Override
      public boolean getFollowAccount() {
        return instance.getFollowAccount();
      }
      /**
       * <code>bool followAccount = 3;</code>
       * @param value The followAccount to set.
       * @return This builder for chaining.
       */
      public Builder setFollowAccount(boolean value) {
        copyOnWrite();
        instance.setFollowAccount(value);
        return this;
      }
      /**
       * <code>bool followAccount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFollowAccount() {
        copyOnWrite();
        instance.clearFollowAccount();
        return this;
      }

      /**
       * <code>repeated string phone = 4;</code>
       * @return A list containing the phone.
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getPhoneList() {
        return java.util.Collections.unmodifiableList(
            instance.getPhoneList());
      }
      /**
       * <code>repeated string phone = 4;</code>
       * @return The count of phone.
       */
      @java.lang.Override
      public int getPhoneCount() {
        return instance.getPhoneCount();
      }
      /**
       * <code>repeated string phone = 4;</code>
       * @param index The index of the element to return.
       * @return The phone at the given index.
       */
      @java.lang.Override
      public java.lang.String getPhone(int index) {
        return instance.getPhone(index);
      }
      /**
       * <code>repeated string phone = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the phone at the given index.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPhoneBytes(int index) {
        return instance.getPhoneBytes(index);
      }
      /**
       * <code>repeated string phone = 4;</code>
       * @param index The index to set the value at.
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setPhone(index, value);
        return this;
      }
      /**
       * <code>repeated string phone = 4;</code>
       * @param value The phone to add.
       * @return This builder for chaining.
       */
      public Builder addPhone(
          java.lang.String value) {
        copyOnWrite();
        instance.addPhone(value);
        return this;
      }
      /**
       * <code>repeated string phone = 4;</code>
       * @param values The phone to add.
       * @return This builder for chaining.
       */
      public Builder addAllPhone(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllPhone(values);
        return this;
      }
      /**
       * <code>repeated string phone = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        copyOnWrite();
        instance.clearPhone();
        return this;
      }
      /**
       * <code>repeated string phone = 4;</code>
       * @param value The bytes of the phone to add.
       * @return This builder for chaining.
       */
      public Builder addPhoneBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addPhoneBytes(value);
        return this;
      }

      /**
       * <code>.Person.Address address = 5;</code>
       */
      @java.lang.Override
      public boolean hasAddress() {
        return instance.hasAddress();
      }
      /**
       * <code>.Person.Address address = 5;</code>
       */
      @java.lang.Override
      public com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address getAddress() {
        return instance.getAddress();
      }
      /**
       * <code>.Person.Address address = 5;</code>
       */
      public Builder setAddress(com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address value) {
        copyOnWrite();
        instance.setAddress(value);
        return this;
        }
      /**
       * <code>.Person.Address address = 5;</code>
       */
      public Builder setAddress(
          com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address.Builder builderForValue) {
        copyOnWrite();
        instance.setAddress(builderForValue);
        return this;
      }
      /**
       * <code>.Person.Address address = 5;</code>
       */
      public Builder mergeAddress(com.hi.dhl.datastore.protobuf.PersonProtos.Person.Address value) {
        copyOnWrite();
        instance.mergeAddress(value);
        return this;
      }
      /**
       * <code>.Person.Address address = 5;</code>
       */
      public Builder clearAddress() {  copyOnWrite();
        instance.clearAddress();
        return this;
      }

      /**
       * <code>.Person.Weekday weekday = 6;</code>
       * @return The enum numeric value on the wire for weekday.
       */
      @java.lang.Override
      public int getWeekdayValue() {
        return instance.getWeekdayValue();
      }
      /**
       * <code>.Person.Weekday weekday = 6;</code>
       * @param value The weekday to set.
       * @return This builder for chaining.
       */
      public Builder setWeekdayValue(int value) {
        copyOnWrite();
        instance.setWeekdayValue(value);
        return this;
      }
      /**
       * <code>.Person.Weekday weekday = 6;</code>
       * @return The weekday.
       */
      @java.lang.Override
      public com.hi.dhl.datastore.protobuf.PersonProtos.Person.Weekday getWeekday() {
        return instance.getWeekday();
      }
      /**
       * <code>.Person.Weekday weekday = 6;</code>
       * @param value The enum numeric value on the wire for weekday to set.
       * @return This builder for chaining.
       */
      public Builder setWeekday(com.hi.dhl.datastore.protobuf.PersonProtos.Person.Weekday value) {
        copyOnWrite();
        instance.setWeekday(value);
        return this;
      }
      /**
       * <code>.Person.Weekday weekday = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeekday() {
        copyOnWrite();
        instance.clearWeekday();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.hi.dhl.datastore.protobuf.PersonProtos.Person();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "name_",
              "age_",
              "followAccount_",
              "phone_",
              "address_",
              "weekday_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0001\u0000\u0001\u0208\u0002\u0004" +
                "\u0003\u0007\u0004\u021a\u0005\t\u0006\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.hi.dhl.datastore.protobuf.PersonProtos.Person> parser = PARSER;
          if (parser == null) {
            synchronized (com.hi.dhl.datastore.protobuf.PersonProtos.Person.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.hi.dhl.datastore.protobuf.PersonProtos.Person>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Person)
    private static final com.hi.dhl.datastore.protobuf.PersonProtos.Person DEFAULT_INSTANCE;
    static {
      Person defaultInstance = new Person();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Person.class, defaultInstance);
    }

    public static com.hi.dhl.datastore.protobuf.PersonProtos.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Person> PARSER;

    public static com.google.protobuf.Parser<Person> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
